const { GoogleGenAI} = require('@google/genai')
const {z} = require('zod')
const {zodToJsonSchema} = require('zod-to-json-schema')
const ai = new GoogleGenAI({
    apiKey : process.env.GOOGLE_GENAI_API_KEY
})
const interviewReportSchema = z.object({
    matchScore : z.number().describe("The match score between 0 and 100 indicating how well the candidate matches the job description"),
    technicalQuestion : z.array(z.object({
        question : z.string().describe("The technical question can be asked in the interview"),
        intention : z.string().describe("The intention of interviewer behind asking this question"),
        answer : z.string().describe("How to asnwer this question, what points to cover, what approch to take etc.")
    })).describe("Technical questions that can be asked in the interview along with their intention and how to answer them"),

    behavioralQuestion : z.array(z.object({
        question : z.string().describe("The technical question can be asked in the interview"),
        intention : z.string().describe("The intention of interviewer behind asking this question"),
        answer : z.string().describe("How to asnwer this question, what points to cover, what approch to take etc.")
    })).describe("Technical questions that can be asked in the interview along with their intention and how to answer them"),
    
    skillGap : z.array(z.object({
        skill:z.string().describe("The skill which the candidate is lacking"),
        severity:z.enum(['low', 'medium','high']).describe("The severity of this skill gap,i.e. how important is this skill for the job")
    })).describe("List fo skill gaps in the candidates profile along with their severity "),

    preparationPlan : z.array(z.object({
        day : z.number().describe("The day number in the preparation plan, startingg from 1 to 7"),
        focus : z.string().describe("The main focus of this day in the preparation plan, e.g. data structure, ststem design, mock interviews, etc. "),
        tasks: z.array(z.string()).describe("List of tasks to be done on this day to follow the preparation plan, e.g. read a specific book or practice a specific topic, do mock interviews, etc. ")
    })).describe("A day-wise preparation plan for the candidate to follow in order to prepare for the interview effectivlly."),
    title:z.string().describe("The title of the job for which the interview is generated")
})

async function generateInterviewReport({resume,selfDescription,jobDescription}){
    const prompt = `Genreate the inverview report for an condidate with the following details:
    Resume:${resume}
    Self Description:${selfDescription}
    Job Description:${jobDescription}
    `
    const response = await ai.models.generateContent({
        model : "gemini-3-flash-preview", 
        contents: prompt,
        config :{
            responseMimeType: "application/json",
            responseJsonSchema: zodToJsonSchema(interviewReportSchema)
        }
    })
      return JSON.parse(response.text)

}


async function generatePdfFromHtml(htmlContent){
    let browser;
    if (process.env.RENDER || process.env.NODE_ENV === 'production') {
        const chromium = require('@sparticuz/chromium');
        const puppeteerCore = require('puppeteer-core');
        browser = await puppeteerCore.launch({
            args: chromium.args,
            defaultViewport: chromium.defaultViewport,
            executablePath: await chromium.executablePath(),
            headless: chromium.headless,
            ignoreHTTPSErrors: true,
        });
    } else {
        const puppeteer = require('puppeteer');
        browser = await puppeteer.launch({
            args: ['--no-sandbox', '--disable-setuid-sandbox']
        });
    }
    const page = await browser.newPage();
    await page.setContent(htmlContent, {waitUntil : "networkidle0"})
    const pdfBuffer = await page.pdf({
        format : "A4",
        printBackground : true
    })
    await browser.close()
    return pdfBuffer
}



async function generateResumePdf({resume, selfDescription, jobDescription}){
    const resumepdfSchema = z.object({
        html : z.string().describe("The html content of the resume which can be converted to pdf using any library like puppeteer")
    })
 const prompt = `Generate a professional resume PDF in HTML format for a candidate with the following details:
Resume:${resume}
Self Description:${selfDescription}
Job Description:${jobDescription}

Create a beautiful, professional HTML resume that showcases all the information provided. The HTML should be self-contained with inline CSS styling. Return ONLY the JSON response with the "html" field containing the complete HTML content.
the resume should be tailored for the given job description and should highlight the candidate's strengths relevant experiences. the html should be well formatted and structured, making it easy to read and visually appealing.
The resume should not sound like its generated by AI and should be as close as possible to a real human-written resume.
you can highlight the content using colors or different font styles but the overall design should be simple and professional. Avoid using any complex design elements or graphics. focus on the content and its presentation in a clean and organized manner.`

    const response = await ai.models.generateContent({
        model : "gemini-3-flash-preview", 
        contents: prompt,
        config :{
            responseMimeType: "application/json",
            responseSchema: zodToJsonSchema(resumepdfSchema)
}})

const jsonContent = JSON.parse(response.text)

const pdfBuffer = await generatePdfFromHtml(jsonContent.html)
return pdfBuffer
}



module.exports = {generateInterviewReport, generateResumePdf}